### ISSUE TITLE
子图生成模块的实现

### ISSUE THREAD

**Issue by Veronica123123** [PTMZ/IMP_GCN#1]
https://github.com/PTMZ/IMP_GCN/blob/d9ac7fb5d7c6639f13db8b14ae67af3e92da3e60/code/model.py#L199
        for g in range(self.groups):
            temp = cust_mul(g_droped, one_hot_emb[g], 1)
            temp = cust_mul(temp, one_hot_emb[g], 0)
            subgraph_list.append(temp)

你好，关于子图生成模块这一部分，这里没有太理解是什么意思。可以解答一下吗？

**Comment by PTMZ** [comment]
Hi,
我可以用英文解释吗？
![image](https://user-images.githubusercontent.com/1089480/159108384-8d0d0559-3664-4eda-a959-76894952eedc.png)
![image](https://user-images.githubusercontent.com/1089480/159107787-cecde715-9a65-491d-9a18-99b45c4b2326.png)
S_g = one_hot_emb[g].
My code filters out the adjacency matrix along dimensions 1 and 0. If it is still unclear I can explain further.
The code for `cust_mul` function is in `utils.py`
```
def cust_mul(s, d, dim):
    i = s._indices()
    v = s._values()
    dv = d[i[dim,:]]
    return torch.sparse.FloatTensor(i, v * dv, s.size())
```

**Comment by Veronica123123** [comment]
Aha， this picture makes my mind clear. Thanks for your help.
